name: Cowsay Message
description: A cowsay way of showing messages
author: lnxpy

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

# == inputs and outputs ==

inputs:
  name:
    required: false
    description: your name
    default: Alice
  age:
    required: false
    description: your age
    default: 20

outputs:
  message:
    description: cowsay greets you in his way
