name: Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - id: cowsay
        uses: ./
        with:
          name: Sadra
          age: 22

      - name: see what cow says
        run: |
          echo ${{ steps.cowsay.outputs.message }}
